### ISSUE TITLE
undefined vec

### ISSUE THREAD

**Issue by jrounds** [stephenbeckr/fastRPCA#1]
I am completely new to matlab so take this with a grain of salt. (Also I am using a slightly older version of your package for  interoperability with someone else.)

Using the sum option, I got an undefined variable message from vec at:
https://github.com/stephenbeckr/fastRPCA/blob/ffa256afa9f4708799dfb533a56135a113b70c23/solvers/solver_RPCA_constrained.m#L585

I noticed via search elsewhere in your demo code you defined vec as:
  vec = @(X) X(:);

Placing that in front of line 585 fixed the error message.

**Comment by DavidHan008** [comment]
how to run this matlab code

**Comment by andrewssobral** [comment]
@DavidHan008 , just run setup_fastRPCA.m and see fastRPCA/demos/demo_elevatorVideo.m

**Comment by stephenbeckr** [comment]
Hi @jrounds , you're right, I think that was missing. I've added the definition and pushed the changes to the repo (I didn't notice because vec() is automatically defined by some other packages I have, e.g., cvx)
