### ISSUE TITLE
how to Gray picture to Binary image?

### ISSUE THREAD

**Issue by DavidHan008** [stephenbeckr/fastRPCA#2]
how to Gray picture to Binary image

**Comment by andrewssobral** [comment]
Hi @DavidHan008, are you talking about from sparse component to foreground mask (binary image) ? If yes, you just need to apply a hard threshold algorithm to the sparse matrix, please see:
https://github.com/andrewssobral/lrslibrary/blob/master/hard_threshold.m

**Comment by stephenbeckr** [comment]
Thanks @andrewssobral . It sounds like that's it, so I'm closing this issue
